config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  root 'jobs#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @jobs = Job.all.order('created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs = Job.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(jobs_params)

    if @job.save
      redirect_to @job
    else
      render 'new'
    end
  end

  def edit
  end

  def update

    if @job.update(jobs_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  def destroy
    @job.destroy

    redirect_to root_path
  end

  private

  def jobs_params
    params.require(:job).permit(:title, :description, :company, :url, :category_id)
  end

  def find_job
    @job = Job.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job, html: { class: 'form-group' }) do |f| %>

  <div class="form-group">
    <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category"} %>
  </div>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: 'Job Title' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, placeholder: 'Job description' %>
  </div>

  <div class="form-group">
    <%= f.label :company %><br>
    <%= f.text_field :company, placeholder: 'Company Title' %>
  </div>

  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, placeholder: 'Link to Job' %>
  </div>

  <div>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/jobs/index.html.erb
<div class="col-xs-10 col-xs-offset-1" id='job-box'>
  <% @jobs.each do |job| %>

  <div id='job'>
    <h2 id='job-title'><%= link_to job.title, job_path(job) %></h2>

    <p id='job-des'>Description: <%= job.description %></p>

    <%= link_to 'Edit', edit_job_path(job), class: 'btn btn-info' %>
    <%= link_to 'Delete', job_path(job), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
  </div>

  <% end %>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p><%= @job.description %></p>
<p><%= @job.company %></p>

<%= link_to 'Home', root_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobsBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'JobsBoard', root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <% Category.all.each do |category| %>
        <li><%= link_to category.name, jobs_path(category: category.name ) %></li>
        <% end %>
      </ul>
      <%= link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link" %>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>